### ISSUE TITLE
error with destination chain

### ISSUE THREAD

**Issue by Kwaskoff** [BlockscapeNetwork/gravity-bridge-portal#1]
I just want send my asset from Gravity to Osmosis
Why metamask!?
 ![Screenshot from 2023-01-23 00-56-05](https://user-images.githubusercontent.com/15308024/213947349-bbe77e54-ed67-4963-8280-376d696ae20f.png)

Chromium 109, Ubuntu 22.04.1

**Comment by BlockscapeLab** [comment]
@Kwaskoff, in case this error still exists, please enter an issue here: 
https://github.com/BlockscapeNetwork/gravity-bridge-portal-flutter
This repo will be closed.
